// EVMS Question Banks — practice + graded exams
// Distractors written to be genuinely plausible; correct answer rotated across A/B/C/D.

export const QUESTION_BANKS = {
  concepts: [
    { q: "What is the primary reason a program finance analyst — not just the project manager — cares about EVMS data?", options: ["It drives the financial forecast, revenue recognition, and contract profitability", "It's purely a project-management schedule tool with no financial link", "It's only needed to satisfy DCMA audits, not for forecasting", "It sets the negotiated fee at contract award"], correct: 0, explain: "EVMS data (earned value, EAC) feeds the financial forecast, percentage-of-completion revenue, and profit — it's not just a PM tool or an audit checkbox." },
    { q: "BCWS represents:", options: ["The actual cost of work performed to date", "The budgeted cost of work planned to be done by now", "The budgeted cost of the work actually completed", "The total budget at completion for the program"], correct: 1, explain: "BCWS (planned value) is the budgeted cost of work SCHEDULED. Actual cost is ACWP; budgeted cost of work DONE is BCWP; the full budget is BAC." },
    { q: "BCWP is also known as:", options: ["Planned Value", "Actual Cost", "Earned Value", "Budget at Completion"], correct: 2, explain: "BCWP = Earned Value, the budgeted cost of work actually performed. Planned Value is BCWS; Actual Cost is ACWP." },
    { q: "Which value drives percentage-of-completion revenue recognition most directly?", options: ["ACWP (actual cost)", "BCWS (planned value)", "BAC (total budget)", "BCWP (earned value)"], correct: 3, explain: "Percentage-of-completion keys off earned value (BCWP) — the budgeted value of work actually done — not money spent (ACWP) or planned (BCWS)." },
    { q: "If BCWP > ACWP, the contract is:", options: ["Showing favorable cost performance (expanding margin)", "Behind schedule", "Over budget", "Running low on obligated funding"], correct: 0, explain: "BCWP > ACWP means CV is positive — you earned more value than you spent: favorable cost performance. Schedule (BCWP vs BCWS) and funding are separate questions." },
    { q: "A CPI of 0.875 means:", options: ["The program is 87.5% complete", "You're getting $0.875 of value for every $1.00 spent", "You're 12.5% behind schedule", "The program will finish at 87.5% of budget"], correct: 1, explain: "CPI = BCWP/ACWP = 0.875 → $0.875 of earned value per $1 spent (over budget). It isn't a % complete or a schedule measure." },
    { q: "When BCWP < BCWS, what's the finance concern?", options: ["The contract must be over budget", "Profit is automatically lost on the overrun", "Revenue recognition may slip and funding burn needs review", "Actual costs are being overstated"], correct: 2, explain: "BCWP < BCWS is a SCHEDULE shortfall (behind plan). For finance, less earned value can delay percentage-of-completion revenue — it doesn't by itself mean a cost overrun." },
    { q: "Schedule Variance (SV) is calculated as:", options: ["BCWP − ACWP", "BCWS − ACWP", "BAC − BCWP", "BCWP − BCWS"], correct: 3, explain: "SV = BCWP − BCWS (earned minus planned). BCWP − ACWP is COST variance (CV), the common mix-up." },
    { q: "Cost Variance (CV) is calculated as:", options: ["BCWP − ACWP", "BCWP − BCWS", "ACWP − BCWS", "BAC − ACWP"], correct: 0, explain: "CV = BCWP − ACWP (earned minus actual cost). BCWP − BCWS is SCHEDULE variance (SV)." },
    { q: "A program shows SPI = 1.10 and CPI = 0.90. The best finance interpretation is:", options: ["Behind schedule and over budget", "Ahead of schedule but over budget — possibly spending too fast to accelerate", "Ahead of schedule and under budget", "The indices are contradictory and must be erroneous"], correct: 1, explain: "SPI > 1 means ahead of schedule; CPI < 1 means over budget. A classic pattern: buying schedule progress with inefficient spend." },
    { q: "Why is earned value measured in budgeted dollars rather than actual dollars?", options: ["Because actual costs aren't known until final billing", "To make progress look better than it is", "So performance can be compared against the baseline objectively", "Because GAAP mandates budgeted-dollar reporting"], correct: 2, explain: "Measuring earned value in budgeted dollars keeps it on the same scale as the baseline (BCWS), so variances reflect performance, not just spending." },
    { q: "The sum of all BCWS across the program equals:", options: ["The Estimate at Completion (EAC)", "The total funding obligated", "The management reserve", "The Performance Measurement Baseline (its total is the BAC)"], correct: 3, explain: "Time-phased BCWS sums to the PMB, whose total is the Budget at Completion (BAC). EAC is a forecast; funding and MR are separate." },
    { q: "Which scenario most likely triggers an EAC increase and profit adjustment?", options: ["CPI = 0.85, SPI = 0.88", "CPI = 1.05, SPI = 1.02", "CPI = 1.00, SPI = 1.00", "CPI = 0.99, SPI = 1.10"], correct: 0, explain: "A CPI well below 1 (0.85) drives the EAC up via cumulative-CPI methods, pressuring profit. The others are at or above plan and wouldn't force an increase." },
    { q: "Management Reserve (MR) is:", options: ["Profit the contractor sets aside for a rainy day", "Budget held outside the PMB for in-scope unknowns, controlled by the PM", "Funding the government withholds until delivery", "A reserve in the EAC for out-of-scope changes"], correct: 1, explain: "MR is budget (not profit, not funding) held outside the PMB for in-scope unknowns, controlled by the PM. Out-of-scope work needs a contract change, not MR." },
    { q: "The 'BCWP' a CAM claims should be supported by:", options: ["The CAM's professional judgment alone", "The actual cost recorded to date", "An objective earned value technique (milestones, % complete, units)", "The funding currently available"], correct: 2, explain: "Earned value must be claimed via objective EVTs (milestones, units, % complete) — not judgment, and never just the cost incurred." },
    { q: "If a finance analyst sees ACWP rising rapidly while BCWP stays flat, this indicates:", options: ["The program is ahead of schedule", "A funding surplus is building", "Revenue is being recognized faster than planned", "Work is being paid for but value isn't being earned — an efficiency problem"], correct: 3, explain: "Spending (ACWP) up while earned value (BCWP) is flat means CPI is dropping — paying without earning. Revenue (tied to BCWP) would stall, not accelerate." },
    { q: "Why might a program with CPI = 1.0 still concern finance?", options: ["CPI ignores funding constraints, schedule position, and EAC risk on remaining work", "A CPI of 1.0 means the program has failed", "It guarantees the contract will post a loss", "CPI can't be calculated reliably at 1.0"], correct: 0, explain: "CPI = 1.0 is on-budget to date, but it says nothing about funding adequacy, schedule, or whether the remaining work will stay efficient." },
    { q: "The TCPI (To-Complete Performance Index) tells you:", options: ["The cost efficiency achieved so far", "The cost efficiency required on remaining work to hit a target", "The percentage of work completed to date", "The schedule efficiency required to finish on time"], correct: 1, explain: "TCPI is forward-looking: the CPI you'd need on the remaining work to hit a target (BAC or EAC). Efficiency achieved so far is the cumulative CPI." },
    { q: "A finance analyst's variance narrative should primarily connect the variance to:", options: ["The technical root cause and nothing more", "The name of the responsible engineer", "Financial impact: margin, revenue timing, and EAC movement", "The original proposal assumptions"], correct: 2, explain: "A finance variance narrative must tie the variance to its financial consequence — margin, revenue timing, EAC — not stop at the technical cause." },
    { q: "Which best describes the relationship between EVMS and the financial statements?", options: ["They are unrelated reporting systems", "EVMS is purely internal and never touches the financials", "The financial statements drive EVMS, not the other way around", "EVMS earned value and EAC feed revenue recognition and profit booking that flow to the financials"], correct: 3, explain: "Earned value and EAC drive percentage-of-completion revenue and profit, which post to the financial statements — the link runs from EVMS into the financials." },
    { q: "A negative cost variance on a Firm-Fixed-Price contract directly reduces:", options: ["Contractor profit/margin", "The government's available funding", "The contract ceiling price", "The earned value already claimed"], correct: 0, explain: "On FFP the price is fixed, so an overrun (negative CV) comes straight out of contractor profit. The ceiling and earned value aren't reduced by it." },
    { q: "The 'Estimate to Complete' (ETC) represents:", options: ["The total forecasted cost at completion", "The forecasted cost of the remaining work", "The actual cost spent to date", "The projected variance at completion"], correct: 1, explain: "ETC = estimate to complete (remaining work only). EAC = ACWP + ETC is the full forecast; ACWP is spent-to-date; VAC is the variance." },
  ],

  funding: [
    { q: "What's the key difference between budget and funding on a defense program?", options: ["Budget measures what work should cost; funding is the dollars authorized to actually spend", "They are two names for the same dollar amount", "Budget is the cash received; funding is the forecast", "Funding is internal; budget is set by the government"], correct: 0, explain: "Budget is what the work should cost (the plan); funding is appropriated dollars authorized to spend. They're distinct and often don't move together." },
    { q: "RDT&E appropriations (3600) typically fund:", options: ["Production of fielded end items", "Research, development, test, and evaluation work", "Day-to-day operations and maintenance", "Military construction projects"], correct: 1, explain: "3600 RDT&E funds development and test work. Production is Procurement (3010); operations is O&M (3400); construction is MILCON." },
    { q: "Procurement appropriations (3010) have a period of availability of:", options: ["1 year", "2 years", "3 years", "5 years"], correct: 2, explain: "Procurement (3010) is available for 3 years. RDT&E is 2 years; O&M is 1 year." },
    { q: "O&M funds (3400) are characterized by:", options: ["3-year availability for production", "2-year availability for development", "No expiration date", "1-year availability, funding sustainment and operations"], correct: 3, explain: "O&M (3400) is 1-year money for operations and sustainment — the shortest availability of the common colors of money." },
    { q: "Spending RDT&E money on production work would be:", options: ["A potential Anti-Deficiency Act / color-of-money violation", "Perfectly acceptable if the PM approves", "Allowed if it's within the same fiscal year", "A minor administrative issue with no consequence"], correct: 0, explain: "Using development money for production violates the Purpose Statute (color of money) and can trigger Anti-Deficiency Act consequences — not a PM call or a trivial matter." },
    { q: "On an incrementally-funded contract, the finance analyst must manage closely to:", options: ["The full contract ceiling", "Obligated funding released in increments", "The total EAC", "The annual O&M budget"], correct: 1, explain: "On incremental funding you manage to the funding actually obligated (placed on contract) in increments — not the ceiling or the EAC." },
    { q: "'Obligated' funds are best described as:", options: ["Cash already paid to the contractor", "The maximum amount the contract allows", "Funding legally committed/placed on the contract", "Money requested but not yet appropriated"], correct: 2, explain: "Obligated = legally committed onto the contract. Paid-out is 'expended'; the max is the ceiling/authorized; requested-but-not-appropriated isn't funding yet." },
    { q: "When expenditures approach obligated funding with work remaining, the analyst should:", options: ["Stop tracking funding since work is nearly done", "Bill the government for the overage immediately", "Move the costs to a different appropriation", "Initiate a funding action to get more on contract before work stops"], correct: 3, explain: "As spend nears obligated funding with work left, start a funding action to place more money on contract. You can't keep performing without funding, or just reclassify costs." },
    { q: "A program with CPI = 1.08 but only $1M of obligated funding left for $4M of remaining work faces:", options: ["A funding shortfall despite excellent cost efficiency", "No issue — strong CPI covers it", "An automatic profit increase", "A schedule problem only"], correct: 0, explain: "Cost efficiency (CPI 1.08) doesn't create funding. $1M obligated against $4M of remaining work is a funding gap requiring action regardless of CPI." },
    { q: "The 'Limitation of Funds' clause (LOF) is relevant to which contract situation?", options: ["Firm-fixed-price fully funded contracts", "Cost-type incrementally funded contracts", "Time-and-materials commercial contracts", "Grant agreements"], correct: 1, explain: "The Limitation of Funds clause (FAR 52.232-22) governs cost-type, incrementally funded contracts, capping the government's obligation to funds allotted." },
    { q: "Expired funds (past period of availability) can:", options: ["Be used freely for any new requirement", "Be returned to the contractor as profit", "Still liquidate valid prior-year obligations but not fund new ones", "Be converted to a different color of money"], correct: 2, explain: "Expired funds can pay or adjust valid prior-year obligations but cannot fund NEW obligations. They aren't freely reusable or convertible." },
    { q: "Cancelled funds (typically 5 years after expiration) are:", options: ["Available for new obligations again", "Usable to liquidate old obligations", "Automatically reappropriated by Congress", "Gone entirely — no longer available for any purpose"], correct: 3, explain: "After cancellation (typically 5 years past expiration) the funds are gone — not even valid old obligations can be paid from them." },
    { q: "The 'funding profile' on a program represents:", options: ["The time-phased plan of when funding will be available", "The contractor's profit schedule", "The earned value baseline", "The schedule of deliverables"], correct: 0, explain: "The funding profile is the time-phased availability of dollars. It isn't the earned-value baseline (PMB) or the delivery schedule." },
    { q: "Why might finance recommend slowing burn rate even when CPI is strong?", options: ["To artificially lower the CPI", "To stay within available funding until the next increment arrives", "To delay revenue recognition for tax reasons", "Because GAAP caps monthly spend"], correct: 1, explain: "Even with great CPI, you can outrun your funding. Slowing burn keeps spend within obligated funds until the next increment lands." },
    { q: "The 'color of money' concept primarily exists because:", options: ["Contractors prefer separate accounts", "The DoD likes administrative complexity", "Congress appropriates funds for specific purposes with specific time limits", "Banks require segregated funds"], correct: 2, explain: "'Color of money' flows from Congress appropriating funds by purpose and period (the Purpose Statute and time limits) — a legal constraint, not a preference." },
    { q: "Authorized funding (contract ceiling) vs obligated funding — the difference is:", options: ["They are identical", "Obligated is always larger than the ceiling", "Ceiling is what's spent; obligated is the forecast", "Ceiling is the max allowed; obligated is what's actually been placed on contract"], correct: 3, explain: "Authorized/ceiling is the maximum; obligated is what's actually committed onto the contract (and is ≤ the ceiling)." },
    { q: "A spending plan that exceeds the funding profile timeline signals:", options: ["A potential funding gap requiring a funding action or rephasing", "A guaranteed cost overrun", "An accounting error", "Improved cost efficiency"], correct: 0, explain: "If planned spend outpaces when funding becomes available, you face a funding gap — address it with a funding action or by rephasing work before work must stop." },
    { q: "Which is NOT a typical responsibility of program finance regarding funding?", options: ["Tracking obligations against funding", "Approving the appropriations bill in Congress", "Initiating funding actions", "Monitoring expenditure rate vs. funding"], correct: 1, explain: "Program finance tracks obligations, initiates funding actions, and monitors burn — but Congress, not program finance, passes appropriations." },
    { q: "An 'unfunded' but in-scope requirement on an incrementally-funded contract should be:", options: ["Performed anyway and billed later", "Treated as out of scope and dropped", "Flagged — work may need to pause until funding is placed", "Funded out of management reserve"], correct: 2, explain: "In-scope work without funding must be flagged; on an incrementally funded contract, work may have to pause until funds are obligated. MR is budget, not funding." },
    { q: "The relationship 'Authorized ≥ Obligated ≥ Expended' should generally hold because:", options: ["It's an accounting coincidence", "GAAP requires the ordering", "The contractor chooses the order", "You can't commit more than authorized, or spend more than committed"], correct: 3, explain: "The chain is causal: you can only obligate up to what's authorized, and only expend what's been obligated — so the inequality must hold." },
    { q: "Why does finance track expenditure rate against funding even on a fully-funded FFP contract?", options: ["To manage cash flow and billing/progress payment timing", "Because FFP contracts are incrementally funded", "To recalculate the color of money", "Because the ceiling changes monthly"], correct: 0, explain: "Even fully funded, tracking spend supports cash-flow and progress-payment/billing timing. FFP isn't incrementally funded and its price is fixed." },
  ],

  contracts: [
    { q: "On a Firm-Fixed-Price (FFP) contract, who bears the cost overrun risk?", options: ["The contractor — entirely", "The government — entirely", "Shared 50/50 by default", "Whoever the contract names later"], correct: 0, explain: "On FFP the price is fixed, so the contractor absorbs 100% of overruns. Sharing is a feature of incentive types (FPIF/CPIF), not FFP." },
    { q: "On a Cost-Plus-Fixed-Fee (CPFF) contract, a cost overrun affects fee how?", options: ["Fee dollars rise with cost", "Fee dollars stay fixed, but fee as a % of cost shrinks", "Fee is eliminated entirely", "The government absorbs the fee loss"], correct: 1, explain: "On CPFF the fee is a fixed dollar amount; an overrun leaves the fee dollars unchanged, so fee as a percent of (now higher) cost falls." },
    { q: "A CPIF contract uses a share ratio (e.g., 80/20) to:", options: ["Split the fee between subcontractors", "Allocate funding across fiscal years", "Share cost overruns/underruns between government and contractor", "Divide the work between two contractors"], correct: 2, explain: "The share ratio splits cost overruns and underruns between government and contractor (e.g., 80/20), adjusting the contractor's fee accordingly." },
    { q: "Which contract type generally carries the HIGHEST risk for the contractor?", options: ["CPFF", "T&M", "CPIF", "FFP"], correct: 3, explain: "FFP puts all cost risk on the contractor (fixed price), making it the highest-risk type. Cost-type shifts risk to the government." },
    { q: "Time-and-Materials (T&M) contracts pay the contractor:", options: ["Fixed hourly labor rates plus materials at cost", "A fixed total price regardless of hours", "Cost plus a fixed fee", "A share of cost savings"], correct: 0, explain: "T&M bills negotiated fixed hourly rates plus materials (often at cost). It's neither a fixed total nor a cost-plus-fee structure." },
    { q: "A $5M cost overrun is MOST damaging to profit on which contract type?", options: ["CPFF", "FFP", "T&M", "CPIF"], correct: 1, explain: "On FFP the overrun comes dollar-for-dollar out of profit. On cost-type the government reimburses cost; on CPIF it's only partly shared." },
    { q: "Award Fee is earned based on:", options: ["A fixed formula tied to cost", "The share ratio at completion", "Periodic subjective government evaluation of performance", "Hours billed times a fee rate"], correct: 2, explain: "Award fee is determined by the government's periodic subjective assessment against award-fee criteria — not a cost formula or share ratio." },
    { q: "On a CPIF contract, the 'point of total assumption' concept is most analogous to which FPIF feature?", options: ["The target cost", "The minimum fee floor", "The award-fee pool", "The ceiling beyond which the contractor bears all further cost"], correct: 3, explain: "The PTA on FPIF is where the contractor begins bearing 100% of additional cost (price hits ceiling) — analogous to the share mechanics reaching their limit. Target cost and fee floors are different points." },
    { q: "For revenue recognition, long-term FFP contracts typically use:", options: ["Percentage-of-completion based on earned value/cost progress", "Recognition only at final delivery and acceptance", "Recognition when cash is received", "Straight-line over the contract term"], correct: 0, explain: "Long-running FFP development/production typically recognizes revenue over time via percentage-of-completion (cost or earned-value based), not just at delivery or on cash." },
    { q: "Why does finance need to know contract type BEFORE reacting to a variance?", options: ["It changes the earned value formula", "The same overrun has totally different profit impact across types", "It determines the color of money", "It sets the schedule baseline"], correct: 1, explain: "A $1M overrun devastates FFP profit but is largely reimbursed on cost-type. Contract type determines the financial impact — so you must know it first." },
    { q: "Cost-reimbursable contracts require the contractor to:", options: ["Deliver at a fixed price", "Guarantee a maximum cost", "Only incur allowable, allocable, reasonable costs per FAR", "Waive all fee"], correct: 2, explain: "On cost-reimbursable contracts the government pays allowable, allocable, reasonable costs (per FAR) plus fee — there's no fixed price or cost guarantee." },
    { q: "An incentive fee contract with an 80/20 share ratio: if costs come in $1M under target, the contractor's fee increases by:", options: ["$800K", "$1M", "$0", "$200K"], correct: 3, explain: "With an 80/20 share, the contractor keeps 20% of a $1M underrun = $200K of additional fee (the government keeps the other $800K)." },
    { q: "Which contract type best protects contractor margin when scope/requirements are highly uncertain?", options: ["Cost-type (CPFF/CPIF)", "Firm-fixed-price", "FPIF with a low ceiling", "T&M with capped hours"], correct: 0, explain: "When scope is uncertain, cost-type shifts cost risk to the government, protecting contractor margin. Fixed-price types expose the contractor to that uncertainty." },
    { q: "On FFP, a cost underrun of $2M means:", options: ["It must be refunded to the government", "The contractor keeps it as additional profit", "It's shared per the share ratio", "It reduces the ceiling price"], correct: 1, explain: "On FFP the price is fixed, so a cost underrun is pure additional profit the contractor keeps — no sharing or refund." },
    { q: "The fee on a CPFF contract is typically expressed as:", options: ["A percentage of final actual cost", "A share of the underrun", "A fixed dollar amount negotiated upfront", "An award based on evaluation"], correct: 2, explain: "CPFF fee is a fixed dollar amount set at award. It does not float with final cost — that's the point of 'fixed fee'." },
    { q: "From a finance forecasting view, which contract type makes profit hardest to predict?", options: ["Firm-fixed-price", "CPFF", "T&M", "Award-fee contracts (subjective scoring)"], correct: 3, explain: "Award fee depends on subjective government evaluations, making the earned fee — and thus profit — the hardest to forecast." },
    { q: "Under percentage-of-completion, if a contract becomes a forecasted loss, finance must:", options: ["Recognize the entire estimated loss immediately", "Spread the loss over remaining periods", "Defer the loss to contract close", "Only disclose it in the footnotes"], correct: 0, explain: "Under percentage-of-completion (and ASC 606), a forecasted contract loss is recognized in full immediately — not spread or deferred." },
    { q: "An FPIF (Fixed-Price-Incentive-Firm) contract differs from FFP by:", options: ["Having no price ceiling at all", "Including a target cost, target profit, ceiling price, and share ratio", "Reimbursing all costs plus fee", "Paying hourly rates plus materials"], correct: 1, explain: "FPIF adds target cost, target profit, a ceiling price, and a share ratio (incentive mechanics) on top of a fixed-price structure — unlike flat FFP." },
    { q: "Why is labor rate management especially critical on T&M contracts?", options: ["Because materials are billed at a large markup", "Because hours billed are unlimited", "Profit depends on the spread between billed rates and actual labor cost", "Because the government sets the labor rates"], correct: 2, explain: "On T&M, billed labor rates are fixed; profit is the spread between those rates and your actual labor cost — so managing actual cost per hour is critical." },
    { q: "When a finance analyst sees a deteriorating EAC on an FFP contract approaching the contract value, the urgent concern is:", options: ["A schedule slip only", "A funding color-of-money issue", "A minor margin dip to monitor", "The contract heading toward a loss position requiring immediate recognition"], correct: 3, explain: "On FFP, an EAC approaching the fixed price means margin is vanishing; if EAC exceeds price, a forward loss must be recognized immediately. That's the urgent flag." },
  ],
};

export const getQuestions = (moduleId, count) => {
  const bank = QUESTION_BANKS[moduleId] || [];
  const shuffled = [...bank].sort(() => Math.random() - 0.5);
  return count ? shuffled.slice(0, count) : shuffled;
};
